apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: analytics production pipeline 1
  annotations:
    github.com/project-slug: Dmitry-Kober/backstage-playground
spec:
  type: other
  lifecycle: unknown
  owner: Dmitrii Kober
