apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  annotations:
    platform: ${{ values.platform }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: ${{ values.type }}
  lifecycle: ${{ values.lifecycle }}
  owner: ${{ values.owner }}
  subcomponentOf: root
